services:
  comprovante-bot:
    build: .
    environment:
      - BASE_DOWNLOAD_DIR=/data
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - LOG_LEVEL=INFO
